[package]
name = "gotham-zip"
version = "0.1.0"
authors = ["cncgl <concigel@gmail.com>"]
edition = "2018"

[dependencies]
gotham = "0.3.0"
gotham_derive = "*"

hyper = "0.12"
mime = "0.3"
serde = "1"
serde_derive = "1"
